name: Deployment Pipeline

on:
  push:
    branches:
      - 'test'
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-verison: '14'
      - name: Install dependencies
        run: npm i
      - name: test
        run: npm test
